[release]
product = "runseal"
authority = "https://releases.runseal.perish.uk"
binaries = ["runseal"]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
]
skill = true

[release.cargo]
registry = "perish"
packages = ["runseal"]

[[document]]
strategy = "agent"
source = [{ path = ".", seal = "3335a18db547857529895f3c385424dda28ed98a2f450c7e5fadbca58477003d" }]
target-seal = "d2955a1ebeb295b5ec000ebeb85ee134e3241219e4ca8fc3217acd2c4e993a89"

[[document]]
strategy = "brief"
name = "runseal"
source = [{ path = "app/src", seal = "2b89418e6973e5adc226386bf2075ac88e0c4ca596a157ee2a28237a3d1d5aea" }]
target-seal = "3c0b995e068c72ec6497d6cbe1cd46d0ad39ca82759d89076e587ad47059524c"
