[release]
product = "runseal"
authority = "https://releases.runseal.perish.uk"
binaries = ["runseal"]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
]
skill = true

[release.cargo]
registry = "perish"
packages = ["runseal"]

[[document]]
strategy = "agent"
source = [{ path = ".", seal = "96746690a48a8c927974cd14bc9cf13394857f4895980d7303aad515b66b81de" }]
target-seal = "d8ddab714ca7c038676f7d3ba0672147da4925ad9a143146bffe7ec264b8e720"

[[document]]
strategy = "brief"
name = "runseal"
source = [{ path = "app/src", seal = "9e859f1e651f0637317be5ab2ebc163d9c829095b7d5f60839fa1e1d09d574dd" }]
target-seal = "303f343c324892cb4a05f2f82b250ebe73266b6e3ef9ef6d34d7de088bfc8f96"
