[package]
name = "runseal-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "runseal"
path = "src/main.rs"

[features]
default = ["managed-skill"]
managed-skill = ["dep:plumb"]

[dependencies]
runseal = { path = "../lib", version = "=0.17.0" }
plumb = { version = "=0.39.0", registry = "perish", features = ["skill"], optional = true }
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tempfile = "3.12"
